---
menus:
  pundit_name: 菜单管理
  pundit_groups:
    create:
      pundit_name: show
      pundits: new, create
    show:
      pundit_name: show
      pundits: show, index
    destroy:
      pundit_name: destroy
      pundits: destroy
