---
roles:
  pundit_name: 角色管理
  pundit_groups:
    create:
      pundit_name: 新增
      pundits: new,create
    show:
      pundit_name: 查看
      pundits: show,index
    edit:
      pundit_name: 编辑
      pundits: edit,update
    destroy:
      pundit_name: 删除
      pundits: destroy
    pundit:
      pundit_name: pundit
      pundits: pundit_groups,pundit_groups_save
    menus:
      pundit_name: menus
      pundits: menus,menus_save
