---
users:
  pundit_name: users
  pundit_groups:
    create:
      pundit_name: 新增
      pundits: new,create
    show:
      pundit_name: 查看
      pundits: show,index
    edit:
      pundit_name: 编辑
      pundits: edit,update
    destroy:
      pundit_name: 删除
      pundits: destroy
    search:
      pundit_name: search
      pundits: search
